# Установите значение TPS вашего сервера при котором,
# мы будем удалять весь падающий песок, гравий и сухой бетон

TPS_THRESHOLD: 18.5

# Установите MSPT при котором будут удаляться лодки и вагонедки

MSPT_THRESHOLD: 50.0

# Сколько должно быть вагонеток или лодок в 1 блоке при MSPT равном MSPT_THRESHOLD

MAX_ENTITIES_PER_BLOCK: 10